version: "3.9"

services:
  web:
    container_name: web
    build: .
    ports:
      - 8000:8000
    env_file:
      - ./src/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    build: ./psql_Docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5